In [60]:
import pandas as pd
import matplotlib.pyplot as plt

In [61]:
df = pd.read_csv("word_dimensions_canon_cardinality.csv")

In [62]:
linton = pd.read_csv("linton.csv", header = 0)

In [ ]:
from trace_and_dimension_calculations.canon import canonical_word
import trace_and_dimension_calculations.canon as canon
import importlib
importlib.reload(canon)

aaabaabbbabAb

In [70]:
linton["canon"] = linton["Relator"].apply(
    lambda w: ''.join(canon.canonical_word(w, use_swap=True))
    if isinstance(w, str) and set(w) <= {'a', 'b', 'A', 'B'}
    else None
)

In [71]:
linton["Dimension"] = linton["canon"].map(df.set_index("word")["dimension"])
linton["Zariski Dense Dimension"] = linton["canon"].map(df.set_index("word")["dimensionZDense"])

In [72]:
linton

,Relator,Name,Number of Generators,Torsion,Abelianisation,Small Cancellation,Center,Free-by-cyclic,Geometric,Manifold,Knot,Link Exterior,Further Information,References,canon,Dimension,Zariski Dense Dimension
0,NaN,Trivial group,0,False,Z^0,True,NaN,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,aa,C_2,1,a,Z^0+Z/2Z,True,a,False,True,NaN,NaN,NaN,NaN,NaN,aa,1.0,-1.0
2,aaa,C_3,1,a,Z^0+Z/3Z,True,a,False,True,NaN,NaN,NaN,NaN,NaN,aaa,2.0,2.0
3,aaaa,C_4,1,a,Z^0+Z/4Z,True,a,False,True,NaN,NaN,NaN,NaN,NaN,aaaa,2.0,2.0
4,aabb,"T(2,2)",2,False,Z^1+Z/2Z,False,bb,True,True,NaN,NaN,NaN,NaN,NaN,aabb,1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33836,aabABABaBabbAB,NaN,2,False,Z^1,False,NaN,False,False,NaN,NaN,NaN,NaN,NaN,aabAbABABabbAB,1.0,0.0
33837,aabABABaBaBBAb,NaN,2,False,Z^1,False,NaN,False,False,NaN,NaN,NaN,NaN,NaN,aabABABaBaBBAb,1.0,0.0
33838,aabABABaBAbbAB,NaN,2,False,Z^1,False,NaN,True,False,NaN,NaN,NaN,NaN,NaN,aabABABaBAbbAB,1.0,0.0
33839,aabABABAbbABaB,NaN,2,False,Z^1,False,NaN,True,False,NaN,NaN,NaN,NaN,NaN,aabABABAbbABaB,1.0,0.0
33840,aabABABAbAbbAB,NaN,2,False,Z^1,False,NaN,True,False,NaN,NaN,NaN,NaN,NaN,aabABABAbAbbAB,1.0,0.0

In [73]:
linton[
    (linton["Dimension"].isna()) &
    linton["Relator"].str.fullmatch(r"[abAB]+")
]

Empty DataFrame
Columns: [Relator, Name, Number of Generators, Torsion, Abelianisation, Small Cancellation, Center, Free-by-cyclic, Geometric, Manifold, Knot, Link Exterior, Further Information, References, canon, Dimension, Zariski Dense Dimension]
Index: []

In [75]:
linton.drop(columns=["canon"]).to_csv("linton_updated.csv", index=False)